version: '3'

services:
  communication-api:
    build: .
    ports:
      - "8005:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 